# Netlify configuration file for building and deploying the documentation.

[build]
# This is the command Netlify will run to build your site.
# It executes the script you created above.
command = "./build_docs.sh"

# This is the directory that contains the final, built version of your site.
# pdoc generates the site into the 'docs/' folder.
publish = "docs/"

[build.environment]
# Specify the Python version to ensure a consistent build environment.
PYTHON_VERSION = "3.8"
